AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3BUCKETJPG:
    Type: AWS::S3::Bucket
    Properties:        
       BucketName: "s3bucketforjgep52"
       VersioningConfiguration: 
           Status: Enabled
       PublicAccessBlockConfiguration:
           BlockPublicAcls: TRUE
           BlockPublicPolicy: TRUE
           IgnorePublicAcls: TRUE
           RestrictPublicBuckets: TRUE
       BucketEncryption:
           ServerSideEncryptionConfiguration:
           - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256      
       LoggingConfiguration:
           DestinationBucketName: "demoudi462"
           LogFilePrefix: logs
       MetricsConfigurations:
           - Id: EntireBucket
       Tags:
           - Key: PROJECT_ID
             Value: JGE-PHASE2
       NotificationConfiguration:
                TopicConfigurations: 
                  - Event: s3:ObjectRemoved:*
                    Topic: 
                       Ref: JPGSNS1Topic
                  - Event: s3:ObjectCreated:*
                    Topic: 
                       Ref: JPGSNS1Topic

  JPGSNS1Topic:
   Properties:
     TopicName: jpgsns12
   Type: "AWS::SNS::Topic"

  JPGSNS1Subcscription:
   Properties:
     TopicArn:
       Ref: JPGSNS1Topic
     Endpoint: uddipta14@yahoo.com
     Protocol: email
     
   Type: "AWS::SNS::Subscription"

  JPGSNSpolicy:
   Properties:
     PolicyDocument:
       Id: JPGTopicPolicy
       Statement:
         -
           Action: "sns:Publish"
           Condition:
             StringEquals:
               aws:SourceAccount: 982838017915
             ArnLike:
               aws:SourceArn: !Join ['', ['arn:aws:s3:*:*:', s3bucketforjgep52 ]]
           Effect: Allow
           Principal:
             AWS: "*"
           Resource:
             Ref: JPGSNS1Topic
     Topics:
       -
         Ref: JPGSNS1Topic
   Type: "AWS::SNS::TopicPolicy"
